field: 2ae052a1-1c6f-45df-a012-99ab1c9e2fe6 # Riders
fieldLayouts:
  935b5a0e-d15d-47d9-a125-67931468108b:
    tabs:
      -
        elements:
          -
            fieldUid: a50390e7-dcdc-403a-b847-8fd76448b721 # Photo
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fd23647a-8a6d-4bbf-a6cd-27e8bca12fb6 # Full Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 58e94733-058f-44e9-bbb8-e2c17ffc7975 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  58e94733-058f-44e9-bbb8-e2c17ffc7975: # Description
    columnSuffix: mubzvcjp
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: 'Short Description of rider'
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a50390e7-dcdc-403a-b847-8fd76448b721: # Photo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: photo
    instructions: 'Upload Rider Photo'
    name: Photo
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:b0e4adc8-ad04-4702-a475-2a7f9dcf8e48' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Upload rider Image'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:b0e4adc8-ad04-4702-a475-2a7f9dcf8e48' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:b0e4adc8-ad04-4702-a475-2a7f9dcf8e48' # Uploads
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  fd23647a-8a6d-4bbf-a6cd-27e8bca12fb6: # Full Name
    columnSuffix: nkbxtapw
    contentColumnType: text
    fieldGroup: null
    handle: fullName
    instructions: 'Please Enter Full Name'
    name: 'Full Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: 'Please enter riders full name'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: riders
name: Rider
sortOrder: 1
