field: 5c21e4f7-18b2-4bac-8422-ac10c7fea892 # Social Links
fieldLayouts:
  dabe8abf-d68b-4d09-a097-a71af4e22626:
    tabs:
      -
        elements:
          -
            fieldUid: 00176a6e-7524-4222-8bd8-ec32fd26d838 # Social Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3afba862-fbba-4943-b21d-4f46d310ace2 # Social Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d63ec04e-fa1c-4c12-825a-8b7ecbbffc0a # Social Destination
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3afba862-fbba-4943-b21d-4f46d310ace2: # Social Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: socialImage
    instructions: ''
    name: 'Social Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:b0e4adc8-ad04-4702-a475-2a7f9dcf8e48' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:b0e4adc8-ad04-4702-a475-2a7f9dcf8e48' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  00176a6e-7524-4222-8bd8-ec32fd26d838: # Social Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: socialTitle
    instructions: 'Title to display'
    name: 'Social Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: 'Title to display '
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d63ec04e-fa1c-4c12-825a-8b7ecbbffc0a: # Social Destination
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: socialDestination
    instructions: 'Destination link.'
    name: 'Social Destination'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: socialLink
name: 'Social Link'
sortOrder: 1
