columnSuffix: null
contentColumnType: string
fieldGroup: 050d6ed9-e9f8-4f71-8fc3-75e7e15a2edc # Home
handle: heroImage
instructions: 'Upload Background Image'
name: 'Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:b0e4adc8-ad04-4702-a475-2a7f9dcf8e48' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Upload Background Image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:b0e4adc8-ad04-4702-a475-2a7f9dcf8e48' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:b0e4adc8-ad04-4702-a475-2a7f9dcf8e48' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
