columnSuffix: null
contentColumnType: string
fieldGroup: f6854804-18ce-4ea8-aa6b-d9a98c8d7e22 # Common
handle: photos
instructions: ''
name: Photos
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:b0e4adc8-ad04-4702-a475-2a7f9dcf8e48' # Uploads
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add photos'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:b0e4adc8-ad04-4702-a475-2a7f9dcf8e48' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:b0e4adc8-ad04-4702-a475-2a7f9dcf8e48' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
