dateModified: 1644845283
email:
  fromEmail: razin@teqbuddies.com
  fromName: 'Craft Demo'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    1ba87a3e-f9ef-4839-bb20-b59d0dbc6b75: Header # Header
    2ae052a1-1c6f-45df-a012-99ab1c9e2fe6: Riders # Riders
    2f7f619e-ea34-4355-be54-d7e53cfb58fb: 'Craft Demo' # Craft Demo
    5c7bb0dd-9821-41ea-bb10-c2a43df38abd: 'Short Description' # Short Description
    8f48bc21-fe25-42ab-b89e-236f62ee1649: Home # Home
    34f72a26-9e02-4bf2-a1e4-6e7d965df742: Photos # Photos
    050d6ed9-e9f8-4f71-8fc3-75e7e15a2edc: Home # Home
    58e94733-058f-44e9-bbb8-e2c17ffc7975: Description # Description
    76fa2bd4-5ce4-481f-acba-7d0b089299dd: 'General Pages' # General Pages
    080f32a7-c8ad-46ff-85e3-39d0d0c6e6ce: Footer # Footer
    0855e6ea-0bb2-4738-93b1-0b0137f86445: LinkDestination # LinkDestination
    2033bf89-ee81-45d2-bd2c-a1091e67bbae: 'General Pages' # General Pages
    2551da85-4a80-4ed5-8ad6-f8469fda24c7: Rider # Rider
    28974529-6836-40e3-8bca-6227ce5c52bc: 'Public Schema' # Public Schema
    a1d7b634-d4b2-4418-ab07-3e78bd543b55: 'Rich Text' # Rich Text
    a38ff0c4-3d3f-4caa-8215-aef2a4190547: 'Craft Demo' # Craft Demo
    a50390e7-dcdc-403a-b847-8fd76448b721: Photo # Photo
    ae104b70-3071-4334-9029-a7de5a418204: 'Riders Intro Content' # Riders Intro Content
    afec578d-fe90-45cd-970b-81f2ca31a6f6: 'Featured Story' # Featured Story
    b0e4adc8-ad04-4702-a475-2a7f9dcf8e48: Uploads # Uploads
    b9f762b4-47ec-4ba2-8685-2b314eb70059: 'Stories Listing' # Stories Listing
    cd08d6bd-7d7f-4d1e-a22e-0284b4899d37: 'Hero title' # Hero title
    d1e6236b-7196-4988-8923-a9c7c7f7ffb2: Links # Links
    da4a3bec-f9f1-4129-a2eb-cf90b83fb4ce: Home # Home
    df2bab60-a886-42d3-bc52-4456bfc43546: 'Stories Listing' # Stories Listing
    e326a306-0601-4c92-9e45-f9774cc4b58d: Stories # Stories
    e7923221-21b0-4634-a1ea-1678d244ac8a: Links # Links
    f556b2d3-247d-41ed-bfaf-c1f6db39b1bd: Stories # Stories
    f6854804-18ce-4ea8-aa6b-d9a98c8d7e22: Common # Common
    fbe07919-3825-40ce-9eb4-90a19ac82ec7: 'Hero Image' # Hero Image
    fd23647a-8a6d-4bbf-a6cd-27e8bca12fb6: 'Full Name' # Full Name
    ff5f4b02-20f2-4bf1-afa8-9934973bef97: 'Display Title' # Display Title
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: 'Craft Demo'
  schemaVersion: 3.7.32
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
