defaultPlacement: end
enableVersioning: true
handle: generalPages
name: 'General Pages'
propagationMethod: all
siteSettings:
  a38ff0c4-3d3f-4caa-8215-aef2a4190547: # Craft Demo
    enabledByDefault: true
    hasUrls: true
    template: general.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 2
  uid: d8185990-7629-4be4-a1ba-0f3d794de3b9
type: structure
