defaultPlacement: end
enableVersioning: true
handle: stories
name: Stories
propagationMethod: all
siteSettings:
  a38ff0c4-3d3f-4caa-8215-aef2a4190547: # Craft Demo
    enabledByDefault: true
    hasUrls: true
    template: stories/_entry.twig
    uriFormat: 'stories/{slug}'
type: channel
